### ISSUE TITLE
Inactive Project

### ISSUE THREAD

**Issue by njappboy** [kurrentproject/Kurrent#3]
@kurrentproject Can there be a method provided to allow others to contribute to this blockchain?
How do developers get involved?

**Comment by tkh23** [comment]
I would love to see advancement on this, too. Perhaps a new team of dev could fork it, continue development and remain using same blockchain.

**Comment by njappboy** [comment]
My personal background is not in C unfortunately. C#, javascript, Java, some python, some ruby, some go. @tkh23 any C development on your end?
